"""empty message

Revision ID: 3f170adadc45
Revises: 032aa2e4fecb
Create Date: 2022-04-01 14:31:01.031377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f170adadc45'
down_revision = '032aa2e4fecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('pub_date', sa.DateTime(), nullable=False))
    op.add_column('post', sa.Column('pub_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'pub_date')
    op.drop_column('comment', 'pub_date')
    # ### end Alembic commands ###
